/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Veterinaria;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maycol
 */
public class Cliente extends javax.swing.JFrame {

    int i, cedula;
    int aux, filaSeleccionada, filasTotales = 0;
    int cedulaDue, cedulaperr;
    boolean validador1 = false, aux1 = false, auxAct = false;
    String nacimientoperr, nombreperr, razaperr, colorperr, nombreP, razaP, colorP, fechaNacP;

    /**
     * 316,239 Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        jPanel1.setBackground(new Color(153, 255, 255, 80));//Transparencia
        jPanel2.setBackground(new Color(153, 255, 255, 80));//Transparencia
        jPanel3.setBackground(new Color(153, 255, 255, 80));//Transparencia
        jPanel7.setBackground(new Color(153, 255, 255, 80));//Transparencia
        jPanel9.setBackground(new Color(153, 255, 255, 80));//Transparencia
        confirmar.setEnabled(false);
        textoCed.setVisible(false);
        textoNom.setVisible(false);
        textoRaza.setVisible(false);
        textoColor.setVisible(false);
        textoNac.setVisible(false);
        cedulaDueno.setVisible(false);
        nombrePerro.setVisible(false);
        textoAlertaFecha1.setVisible(false);
        textoAlertaFecha.setVisible(false);
        raza.setVisible(false);
        color.setVisible(false);
        fechaNac.setVisible(false);
        textoAlerta.setVisible(false);
        DefaultTableModel modelTotal = (DefaultTableModel) tablaTotal.getModel();
        modelTotal.setRowCount(0);
        actualizar(modelTotal);
        tablaTotal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaF = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMascotas = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        textoPerros = new javax.swing.JLabel();
        frameAct = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        raza1 = new javax.swing.JTextField();
        textoCed1 = new javax.swing.JLabel();
        cedulaDueno1 = new javax.swing.JTextField();
        color1 = new javax.swing.JTextField();
        nombrePerro1 = new javax.swing.JTextField();
        textoColor1 = new javax.swing.JLabel();
        textoAlertaFecha1 = new javax.swing.JLabel();
        confirm1 = new javax.swing.JButton();
        textoNom1 = new javax.swing.JLabel();
        textoRaza1 = new javax.swing.JLabel();
        textoAlerta1 = new javax.swing.JLabel();
        textoNac1 = new javax.swing.JLabel();
        fechaNac1 = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        frameReg = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        textoCed = new javax.swing.JLabel();
        textoAlerta = new javax.swing.JLabel();
        cedulaDueno = new javax.swing.JTextField();
        nombrePerro = new javax.swing.JTextField();
        textoColor = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        textoNom = new javax.swing.JLabel();
        textoRaza = new javax.swing.JLabel();
        raza = new javax.swing.JTextField();
        textoNac = new javax.swing.JLabel();
        fechaNac = new com.toedter.calendar.JDateChooser();
        confirmar = new javax.swing.JButton();
        textoAlertaFecha = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTotal = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        registro = new javax.swing.JButton();
        agendar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        act = new javax.swing.JButton();
        abrirTablaMascotas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        tablaF.setMinimumSize(new java.awt.Dimension(452, 433));
        tablaF.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                tablaFWindowClosing(evt);
            }
        });

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(527, 280));

        tablaMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre Perro", "Raza Perro", "Color Perro", "Fecha Nac."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMascotas.setMinimumSize(new java.awt.Dimension(527, 280));
        tablaMascotas.setRowSelectionAllowed(false);
        tablaMascotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMascotasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMascotas);
        if (tablaMascotas.getColumnModel().getColumnCount() > 0) {
            tablaMascotas.getColumnModel().getColumn(0).setResizable(false);
            tablaMascotas.getColumnModel().getColumn(1).setResizable(false);
            tablaMascotas.getColumnModel().getColumn(2).setResizable(false);
            tablaMascotas.getColumnModel().getColumn(3).setResizable(false);
            tablaMascotas.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, -1, 370));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (2).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.setBackground(new java.awt.Color(153, 255, 255));

        textoPerros.setFont(new java.awt.Font("Yu Gothic", 0, 20)); // NOI18N
        textoPerros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPerros.setText("Seleccione la fila que desea modificar!");
        textoPerros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textoPerros, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoPerros)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 450, 50));

        javax.swing.GroupLayout tablaFLayout = new javax.swing.GroupLayout(tablaF.getContentPane());
        tablaF.getContentPane().setLayout(tablaFLayout);
        tablaFLayout.setHorizontalGroup(
            tablaFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaFLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tablaFLayout.setVerticalGroup(
            tablaFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaFLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        frameAct.setMinimumSize(new java.awt.Dimension(279, 360));
        frameAct.setResizable(false);
        frameAct.setSize(new java.awt.Dimension(279, 360));
        frameAct.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                frameActWindowClosing(evt);
            }
        });

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        raza1.setText("Digite raza del perro");
        raza1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raza1MouseClicked(evt);
            }
        });
        jPanel6.add(raza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 260, -1));

        textoCed1.setText("Cédula:");
        jPanel6.add(textoCed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cedulaDueno1.setText("Digite su cédula");
        cedulaDueno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cedulaDueno1MouseClicked(evt);
            }
        });
        cedulaDueno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaDueno1ActionPerformed(evt);
            }
        });
        jPanel6.add(cedulaDueno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 260, -1));

        color1.setText("Digite color del perro");
        color1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color1MouseClicked(evt);
            }
        });
        jPanel6.add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, -1));

        nombrePerro1.setText("Digite el nombre del perro");
        nombrePerro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombrePerro1MouseClicked(evt);
            }
        });
        jPanel6.add(nombrePerro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, -1));

        textoColor1.setText("Color:");
        jPanel6.add(textoColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        textoAlertaFecha1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoAlertaFecha1.setForeground(new java.awt.Color(255, 51, 51));
        textoAlertaFecha1.setText("¿¡Y la fecha!?");
        jPanel6.add(textoAlertaFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        confirm1.setText("Confirmar");
        confirm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirm1MouseClicked(evt);
            }
        });
        jPanel6.add(confirm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        textoNom1.setText("Nombre perro:");
        jPanel6.add(textoNom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        textoRaza1.setText("Raza:");
        jPanel6.add(textoRaza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        textoAlerta1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoAlerta1.setForeground(new java.awt.Color(255, 51, 51));
        textoAlerta1.setText("¡La cédula debe ser de números!");
        jPanel6.add(textoAlerta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        textoNac1.setText("Nacimiento (DD-MM-AA):");
        jPanel6.add(textoNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel6.add(fechaNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 260, -1));

        jPanel7.setBackground(new java.awt.Color(153, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (2).png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 21)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Actualizar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reg.png"))); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout frameActLayout = new javax.swing.GroupLayout(frameAct.getContentPane());
        frameAct.getContentPane().setLayout(frameActLayout);
        frameActLayout.setHorizontalGroup(
            frameActLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameActLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        frameActLayout.setVerticalGroup(
            frameActLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameActLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        frameReg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frameReg.setMinimumSize(new java.awt.Dimension(279, 360));
        frameReg.setResizable(false);
        frameReg.setSize(new java.awt.Dimension(279, 360));
        frameReg.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                frameRegWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                frameRegWindowClosing(evt);
            }
        });

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoCed.setText("Cédula:");
        jPanel5.add(textoCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        textoAlerta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoAlerta.setForeground(new java.awt.Color(255, 51, 51));
        textoAlerta.setText("¡La cédula debe ser de números!");
        jPanel5.add(textoAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        cedulaDueno.setText("Digite su cédula");
        cedulaDueno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cedulaDuenoMouseClicked(evt);
            }
        });
        cedulaDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaDuenoActionPerformed(evt);
            }
        });
        jPanel5.add(cedulaDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 260, -1));

        nombrePerro.setText("Digite el nombre del perro");
        nombrePerro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombrePerroMouseClicked(evt);
            }
        });
        jPanel5.add(nombrePerro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, -1));

        textoColor.setText("Color:");
        jPanel5.add(textoColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        color.setText("Digite color del perro");
        color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorMouseClicked(evt);
            }
        });
        jPanel5.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, -1));

        textoNom.setText(" Nombre perro:");
        jPanel5.add(textoNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        textoRaza.setText("Raza:");
        jPanel5.add(textoRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        raza.setText("Digite raza del perro");
        raza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                razaMouseClicked(evt);
            }
        });
        jPanel5.add(raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 260, -1));

        textoNac.setText("Nacimiento (DD-MM-AA):");
        jPanel5.add(textoNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel5.add(fechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 260, -1));

        confirmar.setText("Confirmar");
        confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarMouseClicked(evt);
            }
        });
        jPanel5.add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 90, 30));

        textoAlertaFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoAlertaFecha.setForeground(new java.awt.Color(255, 51, 51));
        textoAlertaFecha.setText("¿¡Y la fecha!?");
        jPanel5.add(textoAlertaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 21)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Registrar");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (2).png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(61, 61, 61)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reg.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout frameRegLayout = new javax.swing.GroupLayout(frameReg.getContentPane());
        frameReg.getContentPane().setLayout(frameRegLayout);
        frameRegLayout.setHorizontalGroup(
            frameRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameRegLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        frameRegLayout.setVerticalGroup(
            frameRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameRegLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        tablaTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cedula", "nombrePerro", "razaPerro", "colorPerro", "fecha"
            }
        ));
        tablaTotal.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(tablaTotal);
        if (tablaTotal.getColumnModel().getColumnCount() > 0) {
            tablaTotal.getColumnModel().getColumn(0).setResizable(false);
            tablaTotal.getColumnModel().getColumn(1).setResizable(false);
            tablaTotal.getColumnModel().getColumn(2).setResizable(false);
            tablaTotal.getColumnModel().getColumn(4).setResizable(false);
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registro.setText("Registro");
        registro.setMaximumSize(new java.awt.Dimension(95, 23));
        registro.setMinimumSize(new java.awt.Dimension(95, 23));
        registro.setPreferredSize(new java.awt.Dimension(95, 23));
        registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroMouseClicked(evt);
            }
        });
        jPanel4.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 190, 90, 30));

        agendar.setText("Agendar");
        agendar.setMaximumSize(new java.awt.Dimension(95, 23));
        agendar.setMinimumSize(new java.awt.Dimension(95, 23));
        agendar.setPreferredSize(new java.awt.Dimension(95, 23));
        agendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agendarMouseClicked(evt);
            }
        });
        jPanel4.add(agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, 90, 30));

        cancelar.setText("Cancelar");
        cancelar.setMaximumSize(new java.awt.Dimension(95, 23));
        cancelar.setMinimumSize(new java.awt.Dimension(95, 23));
        cancelar.setPreferredSize(new java.awt.Dimension(95, 23));
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });
        jPanel4.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 30));

        modificar.setText("Modificar");
        modificar.setMaximumSize(new java.awt.Dimension(95, 23));
        modificar.setMinimumSize(new java.awt.Dimension(95, 23));
        modificar.setPreferredSize(new java.awt.Dimension(95, 23));
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        jPanel4.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 30));

        act.setText("Actualización");
        act.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actMouseClicked(evt);
            }
        });
        jPanel4.add(act, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, 30));

        abrirTablaMascotas.setText("Mis Mascotas");
        abrirTablaMascotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirTablaMascotasMouseClicked(evt);
            }
        });
        jPanel4.add(abrirTablaMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, 30));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 21)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CITAS");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras (2).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 21)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATOS CLIENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 310, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/65248fa16a08c11099b3a762d98d6600.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actMouseClicked
        tablaF.setVisible(false);
        frameReg.setVisible(true);
        String direccionClientes = "C:\\user";
        File f = new File(direccionClientes);
        String ruta = "C:\\user"; //Carpeta ruta
        String nombreArchivo = "GestionVeterinaria.txt"; //Nombre archivo
        File archivoClientes = new File(ruta, nombreArchivo);
        if (!archivoClientes.exists()) { //No existe el archivo
            JOptionPane.showMessageDialog(null, "No hay ningún dato en el archivo. \nNo hay nada para modificar.");
        } else {
            confirmar.setEnabled(true);
            registro.setEnabled(true);
            abrirTablaMascotas.setEnabled(true);
            act.setEnabled(false);
            textoCed.setVisible(true);
            cedulaDueno.setVisible(true);
            textoNom.setVisible(false);
            textoRaza.setVisible(false);
            textoColor.setVisible(false);
            textoNac.setVisible(false);
            textoAlertaFecha1.setVisible(false);
            textoAlertaFecha.setVisible(false);
            textoAlerta.setVisible(false);
            textoAlerta1.setVisible(false);
            nombrePerro.setVisible(false);
            raza.setVisible(false);
            color.setVisible(false);
            fechaNac.setVisible(false);
            tablaF.setVisible(false);
            cedulaDueno.setText("Digite su cédula");
            aux = 2;
            jLabel5.setText("Actualizar");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_actMouseClicked

    private void actualizar(DefaultTableModel modelTotal) {
        i = 0;
        modelTotal.setRowCount(0);
        System.out.println(modelTotal.getRowCount());
        String direccionClientes = "C:\\user";
        File f = new File(direccionClientes);
        String ruta = "C:\\user"; //Carpeta ruta
        String nombreArchivo = "GestionVeterinaria.txt"; //Nombre archivo
        File archivoClientes = new File(ruta, nombreArchivo);
        if (!archivoClientes.exists()) { //No existe el archivo

        } else {
            try ( Scanner sc = new Scanner(archivoClientes)) {
                while (sc.hasNextLine()) {
                    i++;
                    String linea = sc.nextLine();
                    String data[] = linea.split(",");
                    cedula = Integer.valueOf(data[0]);
                    nombreP = data[1];
                    razaP = data[2];
                    String codP = data[3];
                    fechaNacP = data[4];
                    modelTotal.addRow(new Object[]{cedula, nombreP, razaP, codP, fechaNacP});
                }
            } catch (FileNotFoundException e) {
                System.out.println("El archivo no se encontró");
            }
        }
    }

    private void save(DefaultTableModel modelTotal) {
        String direccionClientes = "C:\\user";
        File f = new File(direccionClientes);
        String ruta = "C:\\user"; //Carpeta ruta
        String nombreArchivo = "GestionVeterinaria.txt"; //Nombre archivo
        File archivoClientes = new File(ruta, nombreArchivo);
        if (!archivoClientes.exists()) { //No existe el archivo
            f.mkdir();
            try {
                archivoClientes.createNewFile();
            } catch (IOException ex) {
                System.out.println("Error");
            }
        }
        try ( FileWriter fw = new FileWriter(archivoClientes.getAbsoluteFile(), true)) {
            BufferedWriter bw = new BufferedWriter(fw);

            //casting
            System.out.println("aaa" + modelTotal.getRowCount());
            while (i < modelTotal.getRowCount()) {
                int cedulaP = Integer.valueOf(String.valueOf(modelTotal.getValueAt(i, 0)));
                nombreP = String.valueOf(modelTotal.getValueAt(i, 1));
                razaP = String.valueOf(modelTotal.getValueAt(i, 2));
                colorP = String.valueOf(modelTotal.getValueAt(i, 3));
                String fechaNacimientoP = String.valueOf(modelTotal.getValueAt(i, 4));
                bw.write(cedulaP + "," + nombreP + "," + razaP + "," + colorP + "," + fechaNacimientoP);
                bw.newLine();
                i++;
            }
            bw.flush();
            bw.close();
            fw.close();
        } catch (IOException e) {
            System.out.println("Error al crear archivo");
        }
    }

    private void abrirTablaMascotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirTablaMascotasMouseClicked
        tablaF.setVisible(false);
        frameReg.setVisible(true);
        confirmar.setEnabled(true);
        registro.setEnabled(true);
        act.setEnabled(true);
        abrirTablaMascotas.setEnabled(false);
        tablaMascotas.setRowSelectionAllowed(false);
        textoPerros.setText("Sus Mascotas");
        textoCed.setVisible(true);
        cedulaDueno.setVisible(true);
        textoNom.setVisible(false);
        textoRaza.setVisible(false);
        textoAlertaFecha1.setVisible(false);
        textoAlertaFecha.setVisible(false);
        textoAlerta.setVisible(false);
        textoAlerta1.setVisible(false);
        textoColor.setVisible(false);
        textoNac.setVisible(false);
        nombrePerro.setVisible(false);
        raza.setVisible(false);
        color.setVisible(false);
        fechaNac.setVisible(false);
        cedulaDueno.setText("Digite su cédula");
        aux = 3;
        jLabel5.setText("Mis Mascotas");
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirTablaMascotasMouseClicked


    private void tablaMascotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMascotasMouseClicked
        if (aux != 3) {
            frameAct.setVisible(true);
            textoAlerta1.setVisible(false);
            DefaultTableModel model = (DefaultTableModel) tablaMascotas.getModel();
            DefaultTableModel modelTotal = (DefaultTableModel) tablaTotal.getModel();
            filaSeleccionada = tablaMascotas.getSelectedRow();
            cedulaDueno1.setText(String.valueOf(model.getValueAt(filaSeleccionada, 0)));
            nombrePerro1.setText(String.valueOf(model.getValueAt(filaSeleccionada, 1)));
            raza1.setText(String.valueOf(model.getValueAt(filaSeleccionada, 2)));
            color1.setText(String.valueOf(model.getValueAt(filaSeleccionada, 3)));
            String aux123 = String.valueOf(model.getValueAt(filaSeleccionada, 4));
            try {
                Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(aux123);
                fechaNac1.setDate(date1);
            } catch (ParseException ex) {
                Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (int j = 0; j < modelTotal.getRowCount(); j++) {
                if ((String.valueOf(modelTotal.getValueAt(j, 0)).equals(String.valueOf(model.getValueAt(filaSeleccionada, 0)))) && (String.valueOf(modelTotal.getValueAt(j, 1)).equals(String.valueOf(model.getValueAt(filaSeleccionada, 1)))) && (String.valueOf(modelTotal.getValueAt(j, 2)).equals(String.valueOf(model.getValueAt(filaSeleccionada, 2)))) && (String.valueOf(modelTotal.getValueAt(j, 3)).equals(String.valueOf(model.getValueAt(filaSeleccionada, 3)))) && (String.valueOf(modelTotal.getValueAt(j, 4)).equals(String.valueOf(model.getValueAt(filaSeleccionada, 4))))) {
                    modelTotal.removeRow(j);
                    j = modelTotal.getRowCount();
                    //////
                }
            }
            tablaF.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMascotasMouseClicked

    private void cedulaDueno1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedulaDueno1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaDueno1MouseClicked

    private void cedulaDueno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaDueno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaDueno1ActionPerformed

    private void nombrePerro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombrePerro1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePerro1MouseClicked

    private void raza1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raza1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_raza1MouseClicked

    private void color1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_color1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_color1MouseClicked

    private void confirm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirm1MouseClicked
        boolean auxCon = false;
        textoAlertaFecha1.setVisible(false);
        textoAlerta1.setVisible(false);
        try {
            cedulaDue = 0;
            cedulaDue = Integer.valueOf(cedulaDueno1.getText());
        } catch (java.lang.NumberFormatException x) {
            auxCon = true;
            textoAlerta1.setText("Sin letras y entre 1-10 dígitos");
            textoAlerta1.setVisible(true);
        }
        if ("".equals(cedulaDueno.getText())) {
            textoAlerta1.setText("La cédula no puede estar vacía");
        }
        if (auxCon != true) {
            try {
                String dia = Integer.toString(fechaNac1.getCalendar().get(Calendar.DAY_OF_MONTH));
                String mes = Integer.toString(fechaNac1.getCalendar().get(Calendar.MONTH) + 1);
                String year = Integer.toString(fechaNac1.getCalendar().get(Calendar.YEAR));
                DefaultTableModel modelTotal = (DefaultTableModel) tablaTotal.getModel();
                aux = 1;
                auxAct = true;
                confirmarMouseClicked(evt);
                auxAct = false;
                resave(modelTotal);
                frameAct.setVisible(false);
            } catch (java.lang.NullPointerException x) {
                textoAlertaFecha1.setVisible(true);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm1MouseClicked

    private void frameActWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frameActWindowClosing
        abrirTablaMascotas.setEnabled(true);
        registro.setEnabled(true);
        act.setEnabled(true);
        textoAlertaFecha1.setVisible(false);
        textoAlertaFecha.setVisible(false);
        textoAlerta.setVisible(false);
        textoAlerta1.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_frameActWindowClosing

    private void tablaFWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_tablaFWindowClosing
        abrirTablaMascotas.setEnabled(true);
        registro.setEnabled(true);
        act.setEnabled(true);
        textoAlertaFecha1.setVisible(false);
        textoAlertaFecha.setVisible(false);
        textoAlerta.setVisible(false);
        textoAlerta1.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaFWindowClosing

    private void registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseClicked
        if (frameReg.isVisible() && textoNom.isVisible()) {

        } else {
            frameReg.setVisible(true);
            confirmar.setEnabled(true);
            registro.setEnabled(false);
            act.setEnabled(true);
            textoCed.setVisible(true);
            textoNom.setVisible(true);
            textoColor.setVisible(true);
            textoRaza.setVisible(true);
            textoNac.setVisible(true);
            textoAlertaFecha1.setVisible(false);
            textoAlertaFecha.setVisible(false);
            textoAlerta.setVisible(false);
            textoAlerta1.setVisible(false);
            abrirTablaMascotas.setEnabled(true);
            cedulaDueno.setVisible(true);
            nombrePerro.setVisible(true);
            raza.setVisible(true);
            color.setVisible(true);
            fechaNac.setVisible(true);
            tablaF.setVisible(false);
            cedulaDueno.setText("Digite su cédula");
            nombrePerro.setText("Digite el nombre del perro");
            raza.setText("Digite raza del perro");
            color.setText("Digite color del perro");
            aux = 1;
            jLabel5.setText("Registrar");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_registroMouseClicked

    private void frameRegWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frameRegWindowClosing
        abrirTablaMascotas.setEnabled(true);
        registro.setEnabled(true);
        act.setEnabled(true);
        textoAlertaFecha1.setVisible(false);
        textoAlertaFecha.setVisible(false);
        textoAlerta.setVisible(false);
        textoAlerta1.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_frameRegWindowClosing

    private void frameRegWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frameRegWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_frameRegWindowClosed

    private void confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarMouseClicked
        textoAlerta1.setVisible(false);
        try {
            if (aux == 3 || aux == 2) {
                validador1 = false;
                if (validador1 == false) {
                    validador1 = true;
                    try {
                        cedulaDue = 0;
                        cedulaDue = Integer.valueOf(cedulaDueno.getText());
                    } catch (java.lang.NumberFormatException x) {
                        validador1 = false;
                        textoAlerta.setText("Sin letras y entre 1-10 dígitos");
                        textoAlerta.setVisible(true);
                    }
                    if ("".equals(cedulaDueno.getText())) {
                        textoAlerta.setText("La cédula no puede estar vacía");
                    }
                }
                if ((validador1 = true) && (cedulaDue != 0) && (!"".equals(cedulaDueno.getText()))) {
                    if (aux == 2) {
                        tablaMascotas.setRowSelectionAllowed(true);
                        textoPerros.setText("Seleccione la fila que desea modificar!");
                    }
                    String direccionClientes = "C:\\user";
                    File f = new File(direccionClientes);
                    String ruta = "C:\\user"; //Carpeta ruta
                    String nombreArchivo = "GestionVeterinaria.txt"; //Nombre archivo
                    File archivoClientes = new File(ruta, nombreArchivo);
                    if (!archivoClientes.exists()) { //No existe el archivo
                        JOptionPane.showMessageDialog(null, "No hay ningún dato en el archivo. \nNo hay ningún cliente aún.");
                    } else {
                        DefaultTableModel model = (DefaultTableModel) tablaMascotas.getModel();
                        try ( Scanner sc = new Scanner(archivoClientes)) {
                            model.setRowCount(0);
                            while (sc.hasNextLine()) {
                                String linea = sc.nextLine();
                                String data[] = linea.split(",");
                                if (Integer.valueOf(data[0]) == cedulaDue) {
                                    cedula = Integer.valueOf(data[0]);
                                    nombreP = data[1];
                                    razaP = data[2];
                                    String codP = data[3];
                                    fechaNacP = data[4];
                                    model.addRow(new Object[]{cedula, nombreP, razaP, codP, fechaNacP});
                                }
                            }
                        } catch (FileNotFoundException e) {
                            System.out.println("El archivo no se encontró");
                        }
                    }
                    frameReg.setVisible(false);
                    tablaF.setVisible(true);
                }
            } else {
                textoAlertaFecha.setVisible(false);
                validador1 = false;
                if (validador1 == false) {
                    validador1 = true;
                    try {
                        cedulaDue = 0;
                        if (auxAct == true) {
                            cedulaDue = Integer.valueOf(cedulaDueno1.getText());
                        } else {
                            cedulaDue = Integer.valueOf(cedulaDueno.getText());
                        }
                    } catch (java.lang.NumberFormatException x) {
                        validador1 = false;
                        if (auxAct == true) {
                            textoAlerta1.setVisible(true);
                            textoAlerta1.setText("Sin letras y entre 1-10 dígitos");
                        } else {
                            textoAlerta.setVisible(true);
                            textoAlerta.setText("Sin letras y entre 1-10 dígitos");
                        }
                    }
                    if ("".equals(cedulaDueno.getText())) {
                        if (auxAct == true) {
                            textoAlerta1.setText("La cédula no puede estar vacía");
                        } else {
                            textoAlerta.setText("La cédula no puede estar vacía");
                        }
                    }
                }
                if ((validador1 == true) && (cedulaDue != 0) && (!"".equals(cedulaDueno.getText()))) {
                    textoAlerta.setVisible(false);
                    DefaultTableModel modelTotal = (DefaultTableModel) tablaTotal.getModel();
                    if (auxAct == true) {
                        cedula = Integer.valueOf(cedulaDueno1.getText());
                        nombreP = nombrePerro1.getText();
                        razaP = raza1.getText();
                        colorP = color1.getText();
                        String dia = Integer.toString(fechaNac1.getCalendar().get(Calendar.DAY_OF_MONTH));
                        String mes = Integer.toString(fechaNac1.getCalendar().get(Calendar.MONTH) + 1);
                        String year = Integer.toString(fechaNac1.getCalendar().get(Calendar.YEAR));
                        String fechaNacimientoP = dia + "/" + mes + "/" + year;
                        fechaNacP = fechaNacimientoP;
                    } else {
                        cedula = Integer.valueOf(cedulaDueno.getText());
                        nombreP = nombrePerro.getText();
                        razaP = raza.getText();
                        colorP = color.getText();
                        String dia = Integer.toString(fechaNac.getCalendar().get(Calendar.DAY_OF_MONTH));
                        String mes = Integer.toString(fechaNac.getCalendar().get(Calendar.MONTH) + 1);
                        String year = Integer.toString(fechaNac.getCalendar().get(Calendar.YEAR));
                        String fechaNacimientoP = dia + "/" + mes + "/" + year;
                        fechaNacP = fechaNacimientoP;

                    }
                    modelTotal.addRow(new Object[]{cedula, nombreP, razaP, colorP, fechaNacP});
                    save(modelTotal);
                    confirmar.setEnabled(false);
                    registro.setEnabled(true);
                    act.setEnabled(true);
                    textoCed.setVisible(false);
                    textoNom.setVisible(false);
                    textoRaza.setVisible(false);
                    textoColor.setVisible(false);
                    abrirTablaMascotas.setEnabled(true);
                    textoNac.setVisible(false);
                    cedulaDueno.setVisible(false);
                    nombrePerro.setVisible(false);
                    raza.setVisible(false);
                    color.setVisible(false);
                    fechaNac.setVisible(false);
                    frameReg.setVisible(false);
                }

            }
        } catch (java.lang.NullPointerException x) {
            textoAlertaFecha.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarMouseClicked

    private void razaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_razaMouseClicked
        raza.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_razaMouseClicked

    private void colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorMouseClicked
        color.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_colorMouseClicked

    private void nombrePerroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombrePerroMouseClicked
        nombrePerro.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePerroMouseClicked

    private void cedulaDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaDuenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaDuenoActionPerformed

    private void cedulaDuenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedulaDuenoMouseClicked
        cedulaDueno.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaDuenoMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setVisible(false);
        Usuario user = new Usuario();
        user.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        frameReg.setVisible(false);
        registro.setEnabled(true);
        act.setEnabled(true);
        abrirTablaMascotas.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        if (act.isEnabled() == true) {
            abrirTablaMascotasMouseClicked(evt);
        } else if (abrirTablaMascotas.isEnabled() == true) {
            actMouseClicked(evt);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        tablaF.setVisible(true);
        frameAct.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void agendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendarMouseClicked
        Agendar Agendy = new Agendar();
        Agendy.setVisible(true);
        this.dispose();                         // TODO add your handling code here:
    }//GEN-LAST:event_agendarMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        Eliminar canceli = new Eliminar();
        canceli.setVisible(true);
        this.dispose(); // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarMouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        Modificar modifi = new Modificar();
        modifi.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_modificarMouseClicked
    private void resave(DefaultTableModel modelTotal) {
        String sDir = "C:\\user";
        File f = new File(sDir);
        String ruta = "C:\\user"; //Carpeta ruta
        String nombreArchivo = "GestionVeterinaria.txt"; //Nombre archivo
        File archivoClientes = new File(ruta, nombreArchivo);

        if (!archivoClientes.exists()) { //No existe el archivo
            f.mkdir();
            try {
                archivoClientes.createNewFile();
            } catch (IOException ex) {
                System.out.println("Error");
            }
        }
        try ( FileWriter fw = new FileWriter(archivoClientes.getAbsoluteFile())) {
            BufferedWriter bw = new BufferedWriter(fw);
            for (int i = 0; i < modelTotal.getRowCount(); i++) {
                //casting 
                int cedulaP = Integer.valueOf(String.valueOf(modelTotal.getValueAt(i, 0)));
                nombreP = String.valueOf(modelTotal.getValueAt(i, 1));
                razaP = String.valueOf(modelTotal.getValueAt(i, 2));
                colorP = String.valueOf(modelTotal.getValueAt(i, 3));
                String fechaNacimientoP = String.valueOf(modelTotal.getValueAt(i, 4));
                bw.write(cedulaP + "," + nombreP + "," + razaP + "," + colorP + "," + fechaNacimientoP);
                bw.newLine();
            }
            bw.flush();
            bw.close();
            fw.close();
        } catch (IOException e) {
            System.out.println("Error al crear archivo");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirTablaMascotas;
    private javax.swing.JButton act;
    private javax.swing.JButton agendar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cedulaDueno;
    private javax.swing.JTextField cedulaDueno1;
    private javax.swing.JTextField color;
    private javax.swing.JTextField color1;
    private javax.swing.JButton confirm1;
    private javax.swing.JButton confirmar;
    private com.toedter.calendar.JDateChooser fechaNac;
    private com.toedter.calendar.JDateChooser fechaNac1;
    private javax.swing.JFrame frameAct;
    private javax.swing.JFrame frameReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombrePerro;
    private javax.swing.JTextField nombrePerro1;
    private javax.swing.JTextField raza;
    private javax.swing.JTextField raza1;
    private javax.swing.JButton registro;
    private javax.swing.JFrame tablaF;
    private javax.swing.JTable tablaMascotas;
    private javax.swing.JTable tablaTotal;
    private javax.swing.JLabel textoAlerta;
    private javax.swing.JLabel textoAlerta1;
    private javax.swing.JLabel textoAlertaFecha;
    private javax.swing.JLabel textoAlertaFecha1;
    private javax.swing.JLabel textoCed;
    private javax.swing.JLabel textoCed1;
    private javax.swing.JLabel textoColor;
    private javax.swing.JLabel textoColor1;
    private javax.swing.JLabel textoNac;
    private javax.swing.JLabel textoNac1;
    private javax.swing.JLabel textoNom;
    private javax.swing.JLabel textoNom1;
    private javax.swing.JLabel textoPerros;
    private javax.swing.JLabel textoRaza;
    private javax.swing.JLabel textoRaza1;
    // End of variables declaration//GEN-END:variables
}
