/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Veterinaria;

import java.awt.Color;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.util.Calendar;

/**
 *
 * @author Maycol
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        jPanel1.setBackground(new Color(153, 255, 255, 80));//Transparencia
    }
    File archivo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cliente = new javax.swing.JButton();
        veterinario = new javax.swing.JButton();
        administrador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO A PERROS PET");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 21)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿Quién va a usar este software?");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 90));

        cliente.setText("Cliente");
        cliente.setMaximumSize(new java.awt.Dimension(85, 23));
        cliente.setMinimumSize(new java.awt.Dimension(85, 23));
        cliente.setPreferredSize(new java.awt.Dimension(85, 23));
        cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteMouseClicked(evt);
            }
        });
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jPanel2.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 100, 40));

        veterinario.setText("Veterinario");
        veterinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veterinarioMouseClicked(evt);
            }
        });
        jPanel2.add(veterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));

        administrador.setText("Administrador");
        administrador.setMaximumSize(new java.awt.Dimension(85, 23));
        administrador.setMinimumSize(new java.awt.Dimension(85, 23));
        administrador.setPreferredSize(new java.awt.Dimension(85, 23));
        administrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                administradorMouseClicked(evt);
            }
        });
        jPanel2.add(administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/17654c57049ee381f68b742779c99162.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseClicked
        Cliente client = new Cliente();
        client.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteMouseClicked

    private void administradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_administradorMouseClicked
        Administrador admin = new Administrador();
        admin.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_administradorMouseClicked

    private void veterinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veterinarioMouseClicked
        Veterinario veterinary = new Veterinario();
        veterinary.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_veterinarioMouseClicked

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administrador;
    private javax.swing.JButton cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton veterinario;
    // End of variables declaration//GEN-END:variables

    private String getText(JTextField hra) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}

/*diaActual = dia.getSelectedItem().toString();
        if (hora1.isSelected()) {
            if ((!"Sabado".equals(diaActual)) && (!"Domingo".equals(diaActual))) {
                if ((((horas <= 13) && (horas >= 8) || (horas <= 18) && (horas >= 14)) && (((Integer.parseInt(minu.getText())) < 60) && (Integer.parseInt(minu.getText())) >= 0))) {
                    Cliente client = new Cliente();
                    client.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "A estas horas la aplicación no está disponible");
                }
            } else {
                System.out.println("Es fin de semana, durante el fin de semana no hay servicio para clientes");
            }
        } else {
            int diaactual = cal.get(Calendar.DAY_OF_WEEK) - 1;
            hora = LocalTime.now();
            if ((diaactual != 6) && (diaactual != 7)) {
                if (((hora.isBefore(LocalTime.parse("13:00:00.00"))) && (hora.isAfter(LocalTime.parse("08:00:00.00")))) || ((hora.isBefore(LocalTime.parse("18:00:00.00"))) && (hora.isAfter(LocalTime.parse("14:00:00.00"))))) {
                    Cliente client = new Cliente();
                    client.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "A estas horas la aplicación no está disponible");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Es fin de semana, durante el fin de semana no hay servicio para clientes");
            }
            System.out.println(diaactual);
        }*/
